"use client";
import {useState,type FormEvent} from 'react';
import styles from './workflow.module.css';
import {demoReply} from '@/lib/workflow-demos';
const welcome={role:'assistant',text:'Hi! I’m the demo product assistant. Ask about ski lessons, meal ordering, uniform orders or working with Ryu.'};
export default function ChatbotDemo(){
 const [messages,setMessages]=useState([welcome]),[draft,setDraft]=useState('');
 const send=(text:string)=>{if(!text.trim())return;setMessages(items=>[...items,{role:'you',text:text.trim()},{role:'assistant',text:demoReply(text)}]);setDraft('');};
 const submit=(event:FormEvent)=>{event.preventDefault();send(draft);};
 return <section className={styles.app}><header className={styles.header}><div><p>CONVERSATION LAB / INTERACTIVE DEMO</p><h1>Ask the assistant</h1><span>A guided chatbot for finding answers and exploring product workflows.</span></div><button onClick={()=>{setMessages([welcome]);setDraft('');}}>Reset conversation</button></header><p className={styles.notice}>Scripted sample responses · no AI service connected · messages stay in this tab</p><div className={styles.columns}><section className={styles.panel}><h2>Conversation</h2><div className={styles.messages} role="log" aria-live="polite" aria-label="Chat conversation">{messages.map((m,index)=><p key={index}><b>{m.role==='you'?'You':'Assistant'}</b><br/>{m.text}</p>)}</div><form onSubmit={submit}><label>Your message<input required value={draft} onChange={e=>setDraft(e.target.value)} placeholder="How do I request a ski lesson?" maxLength={1000}/></label><button>Send message</button></form></section><aside className={styles.panel}><h2>Try a conversation</h2><p>Choose a prompt, then ask a follow-up in your own words.</p><div className={styles.promptList}>{['How do I request a ski lesson?','What happens after a lesson is accepted?','How does the meal cutoff work?','How are uniform costs deducted?','How do I find a cycling guide?','Can I talk to a person?'].map(prompt=><button key={prompt} onClick={()=>send(prompt)}>{prompt}</button>)}</div><p>The prototype demonstrates a chat flow, suggested prompts and a helpful fallback when a question is outside its sample topics.</p></aside></div></section>;
}
