"use client";
import {useState,type FormEvent} from 'react';
import styles from './workflow.module.css';
const guides=[{id:1,name:'Aya',city:'Kyoto',activity:'Culture walk',bio:'Quiet streets, neighborhood markets and local stories.',rate:6000},{id:2,name:'Ren',city:'Kyoto',activity:'Cycling',bio:'A relaxed riverside ride with stops at small local cafés.',rate:4500},{id:3,name:'Mika',city:'Tokyo',activity:'Food tour',bio:'Explore neighborhood food spots with a local.',rate:7000},{id:4,name:'Leo',city:'Tokyo',activity:'Cycling',bio:'City routes, waterfront paths and an easy social pace.',rate:5000}];
export default function GuideMatchingDemo(){
 const [tab,setTab]=useState('Discover'),[city,setCity]=useState('All cities'),[activity,setActivity]=useState('All activities'),[saved,setSaved]=useState<number[]>([]),[requests,setRequests]=useState<{guide:number;date:string;accepted:boolean}[]>([]),[selected,setSelected]=useState(1),[date,setDate]=useState('2026-12-10'),[draft,setDraft]=useState(''),[messages,setMessages]=useState<Record<number,string[]>>({}),[notice,setNotice]=useState('');
 const shown=guides.filter(g=>(city==='All cities'||g.city===city)&&(activity==='All activities'||g.activity===activity));
 const guide=guides.find(g=>g.id===selected)!;
 const request=(event:FormEvent)=>{event.preventDefault();if(requests.some(r=>r.guide===selected&&r.date===date)){setNotice('You already requested this experience on that date.');return;}setRequests(items=>[...items,{guide:selected,date,accepted:false}]);setNotice('Request sent in this demo. Open Requests to play the guide and accept it.');};
 const send=(event:FormEvent)=>{event.preventDefault();if(!draft.trim())return;setMessages(items=>({...items,[selected]:[...(items[selected]??[]),draft.trim()]}));setDraft('');};
 return <section className={styles.app}><header className={styles.header}><div><p>LOCAL CONNECTIONS / INTERACTIVE DEMO</p><h1>Meet Beyond</h1><span>Find a local guide or someone to share a ride, walk or food experience.</span></div><button onClick={()=>{setSaved([]);setRequests([]);setMessages({});setNotice('Demo reset.');}}>Reset demo</button></header><p className={styles.notice}>Fictional profiles · sample prices · no real bookings or messages</p><nav className={styles.tabs} aria-label="Matching views">{['Discover','Saved guides','Requests','Conversation'].map(item=><button key={item} aria-pressed={tab===item} onClick={()=>setTab(item)}>{item}</button>)}</nav>
 {tab==='Discover'&&<div className={styles.toolbar}><label>Destination<select value={city} onChange={e=>setCity(e.target.value)}><option>All cities</option><option>Kyoto</option><option>Tokyo</option></select></label><label>Activity<select value={activity} onChange={e=>setActivity(e.target.value)}>{['All activities','Culture walk','Cycling','Food tour'].map(a=><option key={a}>{a}</option>)}</select></label><p>{shown.length} local experiences match your choices</p></div>}
 {(tab==='Discover'||tab==='Saved guides')&&<div className={styles.cards}>{(tab==='Discover'?shown:guides.filter(g=>saved.includes(g.id))).map(g=><article key={g.id}><span className={styles.avatar}>{g.name[0]}</span><small>{g.city} / {g.activity}</small><h2>{g.name}</h2><p>{g.bio}</p><strong>¥{g.rate.toLocaleString()} / experience</strong><button onClick={()=>setSaved(items=>items.includes(g.id)?items.filter(id=>id!==g.id):[...items,g.id])}>{saved.includes(g.id)?'Saved — remove':'Save guide'}</button><button onClick={()=>{setSelected(g.id);setTab('Conversation');}}>Meet {g.name}</button></article>)}{tab==='Saved guides'&&!saved.length&&<p>No saved guides yet. Discover someone and save their profile.</p>}{tab==='Discover'&&!shown.length&&<p>No matches for these filters. Try another city or activity.</p>}</div>}
 {tab==='Requests'&&<section className={styles.panel}><h2>Your activity requests</h2><p>Play the local guide to accept a request and confirm the experience.</p>{!requests.length&&<p>Open a guide’s conversation to request an experience.</p>}{requests.map((r,index)=>{const g=guides.find(g=>g.id===r.guide)!;return <article key={g.id+r.date} className={styles.row}><div><h3>{g.activity} with {g.name}</h3><p>{g.city} · {r.date}</p></div><span>{r.accepted?'Confirmed':'Waiting for guide'}</span>{!r.accepted&&<button onClick={()=>setRequests(items=>items.map((item,i)=>i===index?{...item,accepted:true}:item))}>Accept as guide</button>}</article>})}</section>}
 {tab==='Conversation'&&<div className={styles.columns}><section className={styles.panel}><h2>Conversation with {guide.name}</h2><p>{guide.city} · {guide.activity}</p><div className={styles.messages}><p>{guide.bio} What would you like to explore?</p>{(messages[selected]??[]).map((message,i)=><p key={i}><b>You:</b> {message}</p>)}</div><form onSubmit={send}><label>Message<input required value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Write a sample message"/></label><button>Send demo message</button></form></section><form className={styles.panel} onSubmit={request}><h2>Plan an experience</h2><p>{guide.activity} with {guide.name} · ¥{guide.rate.toLocaleString()}</p><label>Activity date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><button>Request experience</button></form></div>}
 <p role="status">{notice}</p></section>;
}
