"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import { lessonTotals, mealCounts, uniformGroups, uniformTotal, type Lesson, type MealOrder, type UniformOrder } from "@/lib/workflow-demos";
import styles from "./workflow.module.css";

type Kind="ski-school"|"automobile-operations"|"company-meals"|"uniform-ordering";
const money=(value:number)=>'¥'+value.toLocaleString();
function Frame({name,intro,tabs,tab,setTab,reset,children}:{name:string;intro:string;tabs:string[];tab:string;setTab:(tab:string)=>void;reset:()=>void;children:ReactNode}) {
 return <section className={styles.app}><header className={styles.header}><div><p>WORKFLOW LAB / INTERACTIVE DEMO</p><h1>{name}</h1><span>{intro}</span></div><button onClick={reset}>Reset demo</button></header><p className={styles.notice}>Sample data · changes stay in this tab · no real bookings, orders or payroll actions</p><nav className={styles.tabs} aria-label="Workflow views">{tabs.map(item=><button key={item} aria-pressed={tab===item} onClick={()=>setTab(item)}>{item}</button>)}</nav>{children}</section>;
}
function SkiDemo(){
 const instructors=[{name:"Aki",specialty:"First turns · English / Japanese"},{name:"Mika",specialty:"Family lessons · Japanese"},{name:"Leo",specialty:"Carving · English"}];
 const seed:Lesson[]=[{id:1,customer:"Sample family",instructor:"Mika",date:"2026-12-20",accepted:true,fee:18000},{id:2,customer:"Sample visitor",instructor:"Aki",date:"2026-12-21",accepted:false,fee:18000}];
 const [tab,setTab]=useState('Customer'),[lessons,setLessons]=useState(seed),[instructor,setInstructor]=useState('Aki'),[customer,setCustomer]=useState('Demo guest'),[date,setDate]=useState('2026-12-22'),[message,setMessage]=useState('');
 const request=(event:FormEvent)=>{event.preventDefault();if(lessons.some(l=>l.instructor===instructor&&l.date===date)){setMessage('This instructor already has a request or lesson on that date. Choose another day.');return;}setLessons(items=>[...items,{id:Date.now(),customer:customer.trim(),instructor,date,accepted:false,fee:18000}]);setMessage('Lesson requested. Switch to Instructor to accept it.');};
 return <Frame name="Summit School" intro="Request a lesson, accept it as an instructor, then review school earnings." tabs={['Customer','Instructor','School finances']} tab={tab} setTab={setTab} reset={()=>{setLessons(seed);setMessage('Demo reset.');setTab('Customer');}}>
 {tab==='Customer'&&<div className={styles.columns}><section><h2>Meet the instructors</h2><div className={styles.cards}>{instructors.map((person,index)=><article key={person.name}><span className={styles.avatar}>{person.name[0]}</span><small>INSTRUCTOR 0{index+1}</small><h3>{person.name}</h3><p>{person.specialty}</p><button onClick={()=>setInstructor(person.name)} aria-pressed={instructor===person.name}>{instructor===person.name?'Selected':'Choose instructor'}</button></article>)}</div></section><form className={styles.panel} onSubmit={request}><h2>Request a private lesson</h2><label>Guest name<input required value={customer} onChange={e=>setCustomer(e.target.value)}/></label><label>Instructor<select value={instructor} onChange={e=>setInstructor(e.target.value)}>{instructors.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Lesson date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><p>Full-day lesson · {money(18000)}</p><button type="submit">Request lesson</button><p role="status">{message}</p></form></div>}
 {tab==='Instructor'&&<section className={styles.panel}><h2>Requests & schedule</h2><p>Accepting a request confirms the lesson and creates an invoice in School finances.</p>{lessons.map(lesson=><article className={styles.row} key={lesson.id}><div><h3>{lesson.customer}</h3><p>{lesson.date} · {lesson.instructor} · {money(lesson.fee)}</p></div><span>{lesson.accepted?'Confirmed':'Awaiting acceptance'}</span>{!lesson.accepted&&<button onClick={()=>setLessons(items=>items.map(l=>l.id===lesson.id?{...l,accepted:true}:l))} aria-label={'Accept lesson for '+lesson.customer}>Accept lesson</button>}</article>)}</section>}
 {tab==='School finances'&&<><div className={styles.cards}>{instructors.map(p=>{const totals=lessonTotals(lessons,p.name);return <article key={p.name}><h3>{p.name}</h3><strong>{money(totals.earnings)}</strong><p>{totals.lessons} confirmed lessons · instructor earnings</p><small>Demo split: 70% instructor / 30% school</small></article>})}</div><section className={styles.panel}><h2>Lesson invoices</h2>{lessons.filter(l=>l.accepted).map(l=><article className={styles.row} key={l.id}><div><h3>INV-{String(l.id).slice(-5)} · {l.customer}</h3><p>{l.instructor} · {l.date}</p></div><strong>{money(l.fee)}</strong><span>Issued · sample invoice</span></article>)}</section></>}
 </Frame>;
}

type Vehicle={id:number;model:string;plate:string;inspection:string};
type Task={id:number;vehicle:string;staff:string;problem:string;done:boolean};
function AutomobileDemo(){
 const seed:Vehicle[]=[{id:1,model:'Toyota Aqua',plate:'DEMO-101',inspection:'2026-11-15'},{id:2,model:'Nissan Note',plate:'DEMO-202',inspection:'2026-12-03'}];
 const [tab,setTab]=useState('Vehicles'),[vehicles,setVehicles]=useState(seed),[tasks,setTasks]=useState<Task[]>([{id:1,vehicle:'Toyota Aqua',staff:'Yuki',problem:'Check tire pressure',done:false}]),[rentals,setRentals]=useState<{id:number;vehicle:string;start:string;end:string}[]>([]),[model,setModel]=useState(''),[plate,setPlate]=useState(''),[inspection,setInspection]=useState('2026-12-01'),[vehicle,setVehicle]=useState('Toyota Aqua'),[staff,setStaff]=useState('Yuki'),[problem,setProblem]=useState(''),[start,setStart]=useState('2026-12-10'),[end,setEnd]=useState('2026-12-12'),[message,setMessage]=useState('');
 const add=(event:FormEvent)=>{event.preventDefault();setVehicles(items=>[...items,{id:Date.now(),model:model.trim(),plate:plate.trim(),inspection}]);setModel('');setPlate('');setMessage('Vehicle registered.');};
 const assign=(event:FormEvent)=>{event.preventDefault();setTasks(items=>[...items,{id:Date.now(),vehicle,staff,problem:problem.trim(),done:false}]);setProblem('');setMessage('Problem reported and task assigned.');};
 const rent=(event:FormEvent)=>{event.preventDefault();if(end<start){setMessage('Return date must be on or after pickup.');return;}if(rentals.some(r=>r.vehicle===vehicle&&start<=r.end&&end>=r.start)){setMessage('This vehicle is already booked during those dates.');return;}setRentals(items=>[...items,{id:Date.now(),vehicle,start,end}]);setMessage('Rental reserved in the demo schedule.');};
 const select=<label>Vehicle<select value={vehicle} onChange={e=>setVehicle(e.target.value)}>{vehicles.map(v=><option key={v.id}>{v.model}</option>)}</select></label>;
 return <Frame name="Garage Desk" intro="Register vehicles, plan inspections, assign staff work and reserve rentals." tabs={['Vehicles','Staff tasks','Rentals']} tab={tab} setTab={value=>{setTab(value);setMessage('');}} reset={()=>{setVehicles(seed);setTasks([]);setRentals([]);setVehicle('Toyota Aqua');setMessage('Demo reset.');}}>
 {tab==='Vehicles'&&<div className={styles.columns}><section className={styles.panel}><h2>Fleet & shaken inspections</h2>{vehicles.map(v=><article className={styles.row} key={v.id}><div><h3>{v.model}</h3><p>{v.plate}</p><label>Inspection date for {v.model}<input type="date" value={v.inspection} onChange={e=>setVehicles(items=>items.map(item=>item.id===v.id?{...item,inspection:e.target.value}:item))}/></label></div><span>Registered</span></article>)}</section><form className={styles.panel} onSubmit={add}><h2>Register a vehicle</h2><label>Model<input required value={model} onChange={e=>setModel(e.target.value)}/></label><label>Registration number<input required value={plate} onChange={e=>setPlate(e.target.value)}/></label><label>Shaken inspection<input type="date" required value={inspection} onChange={e=>setInspection(e.target.value)}/></label><button>Register vehicle</button></form></div>}
 {tab==='Staff tasks'&&<div className={styles.columns}><section className={styles.panel}><h2>Assigned work</h2>{tasks.length===0&&<p>No tasks yet. Report a problem to assign one.</p>}{tasks.map(task=><article className={styles.row} key={task.id}><div><h3>{task.problem}</h3><p>{task.vehicle} · assigned to {task.staff}</p></div><button onClick={()=>setTasks(items=>items.map(t=>t.id===task.id?{...t,done:!t.done}:t))}>{task.done?'Completed — reopen':'Mark complete'}</button></article>)}</section><form className={styles.panel} onSubmit={assign}><h2>Report & assign</h2>{select}<label>Staff<select value={staff} onChange={e=>setStaff(e.target.value)}><option>Yuki</option><option>Ren</option><option>Hana</option></select></label><label>Problem or task<textarea required value={problem} onChange={e=>setProblem(e.target.value)}/></label><button>Assign task</button></form></div>}
 {tab==='Rentals'&&<div className={styles.columns}><section className={styles.panel}><h2>Rental schedule</h2>{rentals.length===0&&<p>No bookings yet. Reserve a vehicle to see it here.</p>}{rentals.map(r=><article className={styles.row} key={r.id}><div><h3>{r.vehicle}</h3><p>{r.start} → {r.end}</p></div><button onClick={()=>setRentals(items=>items.filter(item=>item.id!==r.id))}>Cancel reservation</button></article>)}</section><form className={styles.panel} onSubmit={rent}><h2>Reserve a vehicle</h2>{select}<label>Pickup<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Return<input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label><button>Reserve rental</button></form></div>}
 <p role="status">{message}</p></Frame>;
}

function MealDemo(){
 const menu=[{name:'Chicken rice bowl',price:550,emoji:'🍚'},{name:'Vegetable curry',price:500,emoji:'🍛'},{name:'Grilled fish set',price:650,emoji:'🐟'}];
 const seed:MealOrder[]=[{employee:'Aki',meal:menu[0].name},{employee:'Mika',meal:menu[1].name},{employee:'Ren',meal:menu[0].name}];
 const [tab,setTab]=useState('Employee menu'),[orders,setOrders]=useState(seed),[employee,setEmployee]=useState('Demo employee'),[closed,setClosed]=useState(false),[message,setMessage]=useState('');
 const counts=mealCounts(orders,menu.map(item=>item.name));
 const choose=(meal:string)=>{if(closed)return;if(!employee.trim()){setMessage('Enter a sample employee name first.');return;}setOrders(items=>[...items.filter(o=>o.employee!==employee.trim()),{employee:employee.trim(),meal}]);setMessage('Meal selected. Open Kitchen to see updated portion counts.');};
 return <Frame name="Lunch Ledger" intro="Choose lunch before the cutoff, then see exactly what the kitchen needs to prepare." tabs={['Employee menu','Kitchen','Popularity']} tab={tab} setTab={setTab} reset={()=>{setOrders(seed);setClosed(false);setMessage('Demo reset.');}}>
 <div className={styles.toolbar}><label>Employee name<input value={employee} onChange={e=>setEmployee(e.target.value)}/></label><p>Order cutoff: 10:00 · demo clock {closed?'10:05 / closed':'09:30 / open'}</p><button onClick={()=>setClosed(value=>!value)}>{closed?'Reopen ordering':'Simulate cutoff'}</button></div>
 {tab==='Employee menu'&&<div className={styles.cards}>{menu.map(meal=><article key={meal.name}><span className={styles.emoji}>{meal.emoji}</span><h2>{meal.name}</h2><strong>{money(meal.price)}</strong><button disabled={closed} onClick={()=>choose(meal.name)}>{orders.find(o=>o.employee===employee.trim())?.meal===meal.name?'Selected — change anytime before cutoff':'Choose this meal'}</button></article>)}</div>}
 {tab==='Kitchen'&&<section className={styles.panel}><h2>Preparation quantities</h2><p>{orders.length} employee orders · {closed?'Final counts after cutoff':'Orders still open; quantities may change'}</p>{counts.map(item=><article className={styles.row} key={item.meal}><h3>{item.meal}</h3><strong>{item.count} portions</strong></article>)}</section>}
 {tab==='Popularity'&&<section className={styles.panel}><h2>Which meals are popular?</h2><p>Share of today’s sample orders. Change a meal choice to update the analysis.</p>{[...counts].sort((a,b)=>b.count-a.count).map(item=><div className={styles.chart} key={item.meal}><div><span>{item.meal}</span><b>{orders.length?Math.round(item.count/orders.length*100):0}% · {item.count} orders</b></div><meter min={0} max={Math.max(1,orders.length)} value={item.count}/></div>)}</section>}
 <p role="status">{message}</p></Frame>;
}

function UniformDemo(){
 const seed:UniformOrder[]=[{id:1,employee:'Aki',factory:'North factory',garment:'Pants',size:'M',quantity:2,price:3200,deducted:false},{id:2,employee:'Mika',factory:'South factory',garment:'Jacket',size:'S',quantity:1,price:4800,deducted:false}];
 const [tab,setTab]=useState('Employee order'),[orders,setOrders]=useState(seed),[employee,setEmployee]=useState('Demo employee'),[factory,setFactory]=useState('North factory'),[garment,setGarment]=useState('Pants'),[size,setSize]=useState('M'),[quantity,setQuantity]=useState(1),[message,setMessage]=useState('');
 const submit=(event:FormEvent)=>{event.preventDefault();setOrders(items=>[...items,{id:Date.now(),employee:employee.trim(),factory,garment,size,quantity,price:garment==='Pants'?3200:4800,deducted:false}]);setMessage('Order added. Review factory totals and the payroll ledger.');};
 return <Frame name="Uniform Hub" intro="Order uniforms, review factory quantities and simulate employee salary deductions." tabs={['Employee order','Factory totals','Payroll ledger']} tab={tab} setTab={setTab} reset={()=>{setOrders(seed);setMessage('Demo reset.');}}>
 {tab==='Employee order'&&<div className={styles.columns}><section className={styles.panel}><h2>Uniform catalog</h2><div className={styles.cards}>{[{name:'Pants',price:3200,icon:'👖'},{name:'Jacket',price:4800,icon:'🧥'}].map(item=><article key={item.name}><span className={styles.emoji}>{item.icon}</span><h3>{item.name}</h3><strong>{money(item.price)}</strong><button aria-pressed={garment===item.name} onClick={()=>setGarment(item.name)}>{garment===item.name?'Selected':'Select garment'}</button></article>)}</div></section><form className={styles.panel} onSubmit={submit}><h2>Place a uniform order</h2><label>Employee<input required value={employee} onChange={e=>setEmployee(e.target.value)}/></label><label>Factory<select value={factory} onChange={e=>setFactory(e.target.value)}><option>North factory</option><option>South factory</option></select></label><label>Garment<select value={garment} onChange={e=>setGarment(e.target.value)}><option>Pants</option><option>Jacket</option></select></label><label>Size<select value={size} onChange={e=>setSize(e.target.value)}>{['S','M','L','XL'].map(s=><option key={s}>{s}</option>)}</select></label><label>Quantity<input type="number" min={1} max={20} required value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><p>Order total: {money(quantity*(garment==='Pants'?3200:4800))}</p><button>Place order</button></form></div>}
 {tab==='Factory totals'&&<section className={styles.panel}><h2>Orders by factory & garment</h2>{uniformGroups(orders).map(group=><article className={styles.row} key={group.label}><h3>{group.label}</h3><strong>{group.quantity} items</strong></article>)}<p>Total garments: {orders.reduce((sum,order)=>sum+order.quantity,0)}</p></section>}
 {tab==='Payroll ledger'&&<section className={styles.panel}><h2>Employee deductions</h2><p>Simulation only. No salary or payment system is connected.</p>{orders.map(order=><article className={styles.row} key={order.id}><div><h3>{order.employee}</h3><p>{order.factory} · {order.quantity} × {order.garment} / {order.size}</p></div><strong>{money(uniformTotal(order))}</strong><button disabled={order.deducted} onClick={()=>setOrders(items=>items.map(o=>o.id===order.id?{...o,deducted:true}:o))}>{order.deducted?'Deduction recorded':'Simulate salary deduction'}</button></article>)}<p>Pending deductions: {money(orders.filter(o=>!o.deducted).reduce((sum,o)=>sum+uniformTotal(o),0))}</p></section>}
 <p role="status">{message}</p></Frame>;
}

export default function OperationsDemo({kind}:{kind:Kind}){return kind==='ski-school'?<SkiDemo/>:kind==='automobile-operations'?<AutomobileDemo/>:kind==='company-meals'?<MealDemo/>:<UniformDemo/>;}
