"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Flower2, Plus, Search, Trash2, X } from "lucide-react";

type Item={id:number;category:string;decor:string;color:string;owned:boolean;event:boolean;active:boolean};
const colors=["Red","Yellow","Blue","Purple","White","Winged","Rock","Ice"];
const colorHex:Record<string,string>={Red:"#ef5350",Yellow:"#ffd84d",Blue:"#4ea3ff",Purple:"#a978e8",White:"#f4f1e8",Winged:"#ff82ba",Rock:"#7d858b",Ice:"#7ce3f4"};

export default function PikminTracker(){
  const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(true);const [query,setQuery]=useState("");const [filter,setFilter]=useState<"all"|"missing"|"event">("all");const [formOpen,setFormOpen]=useState(false);const [category,setCategory]=useState("");const [decor,setDecor]=useState("");const [selectedColors,setSelectedColors]=useState(colors);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  const load=async()=>{const response=await fetch("/api/admin/pikmin",{cache:"no-store"});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"Could not load the Pikmin collection.")}const data=await response.json();setItems(data);setLoading(false)};
  useEffect(()=>{load().catch(error=>{setError(error instanceof Error?error.message:"Could not load the Pikmin collection.");setLoading(false)})},[]);
  const visible=items.filter(item=>(filter!=="missing"||!item.owned)&&(filter!=="event"||item.event)&&`${item.category} ${item.decor}`.toLowerCase().includes(query.toLowerCase()));
  const groups=useMemo(()=>{const map=new Map<string,Item[]>();visible.forEach(item=>{const key=`${item.category}|||${item.decor}`;map.set(key,[...(map.get(key)||[]),item])});return Array.from(map.entries())},[visible]);
  const owned=items.filter(item=>item.owned).length;const missing=items.length-owned;const categories=new Set(items.map(item=>item.category)).size;
  const toggle=async(item:Item)=>{setItems(current=>current.map(entry=>entry.id===item.id?{...entry,owned:!entry.owned}:entry));const response=await fetch("/api/admin/pikmin",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,owned:!item.owned})});if(!response.ok)setItems(current=>current.map(entry=>entry.id===item.id?item:entry))};
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/admin/pikmin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category,decor,colors:selectedColors,event:true})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Could not add this decor set.");setCategory("");setDecor("");setFormOpen(false);await load()}catch(error){setError(error instanceof Error?error.message:"Could not add this decor set.")}finally{setSaving(false)}};
  const remove=async(categoryName:string,decorName:string)=>{if(!window.confirm(`Remove ${categoryName} / ${decorName} from this tracker?`))return;await fetch(`/api/admin/pikmin?category=${encodeURIComponent(categoryName)}&decor=${encodeURIComponent(decorName)}`,{method:"DELETE"});setItems(current=>current.filter(item=>item.category!==categoryName||item.decor!==decorName))};
  return <main className="pikmin-tracker"><header><Link href="/mission-control"><ArrowLeft/> Mission Control</Link><div><p><Flower2/> PRIVATE COLLECTION MODULE</p><h1>Pikmin Bloom<br/><em>Decor Tracker</em></h1></div><button onClick={()=>setFormOpen(true)}><Plus/> Add event set</button></header>
    <section className="pikmin-stats"><div><span>TOTAL CATALOG</span><strong>{items.length}</strong><small>{categories} categories</small></div><div><span>COLLECTED</span><strong>{owned}</strong><small>{items.length?Math.round(owned/items.length*100):0}% complete</small></div><div><span>STILL MISSING</span><strong>{missing}</strong><small>keep walking</small></div><div className="pikmin-progress"><i style={{width:`${items.length?owned/items.length*100:0}%`}}/></div></section>
    <section className="pikmin-tools"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search category or decor"/></label><div>{(["all","missing","event"] as const).map(value=><button key={value} onClick={()=>setFilter(value)} className={filter===value?"active":""}>{value}</button>)}</div></section>
    {loading?<p className="pikmin-loading">GERMINATING COLLECTION DATA…</p>:<section className="pikmin-groups">{groups.map(([key,group])=>{const [categoryName,decorName]=key.split("|||");const groupOwned=group.filter(item=>item.owned).length;return <article key={key} className={groupOwned===group.length?"complete":""}><header><div><small>{group[0].event?"EVENT DECOR":"LOCATION DECOR"}</small><h2>{categoryName}</h2><p>{decorName}</p></div><div><strong>{groupOwned}/{group.length}</strong>{group[0].event&&<button onClick={()=>remove(categoryName,decorName)} aria-label="Remove event set"><Trash2/></button>}</div></header><div className="pikmin-colors">{group.map(item=><button key={item.id} onClick={()=>toggle(item)} className={item.owned?"owned":""} style={{"--pikmin-color":colorHex[item.color]} as React.CSSProperties}><i/>{item.owned?<Check/>:<X/>}<span>{item.color}</span></button>)}</div></article>})}</section>}
    {formOpen&&<div className="pikmin-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><button type="button" onClick={()=>{setFormOpen(false);setError("")}} aria-label="Close"><X/></button><p>MONTHLY EVENT CATALOG</p><h2>Add a decor set</h2><label>Event or category name<input value={category} onChange={event=>setCategory(event.target.value)} placeholder="July 2026 Event" required maxLength={120}/></label><label>Decor set name<input value={decor} onChange={event=>setDecor(event.target.value)} placeholder="Summer Sticker" required maxLength={160}/></label><fieldset><legend>Available colors</legend>{colors.map(color=><button type="button" key={color} className={selectedColors.includes(color)?"active":""} onClick={()=>setSelectedColors(current=>current.includes(color)?current.filter(item=>item!==color):[...current,color])} style={{"--pikmin-color":colorHex[color]} as React.CSSProperties}><i/>{color}</button>)}</fieldset>{error&&<p className="pikmin-form-error" role="alert">{error}</p>}<button type="submit" disabled={saving||!selectedColors.length}>{saving?"ADDING SET…":"ADD TO COLLECTION"}</button></form></div>}
  </main>;
}
