"use client";
import { useCallback,useEffect,useState } from "react";import Image from "next/image";import Link from "next/link";import { ArrowUpRight,BookOpen,Radio,RefreshCw,Search } from "lucide-react";import FloatingButtons from "@/components/FloatingButtons";import { useLanguage } from "@/app/context/LanguageContext";
type Category="TECH_BUSINESS"|"TRAVEL_CULTURE"|"SKI_SNOW";type ApiPost={id:string;slug:string;title:string;content:string;coverImage?:string|null;createdAt:string;category:Category};
const copy={en:{world:"WORLD 04 · INCOMING TRANSMISSIONS",title1:"Notes from the",title2:"spaces between worlds.",index:"SIGNAL INDEX",entries:"entries received",labels:{TECH_BUSINESS:"Build notes",TRAVEL_CULTURE:"Field notes",SKI_SNOW:"Mountain notes"},filters:["All signals","Build","Explore","Summit"],search:"Search the archive",signal:"SIGNAL",decode:"Decode entry",loading:"Scanning for field notes…",loadError:"The archive could not be reached.",retry:"Try again",empty:"No signal on this frequency.",emptyCopy:"Try another channel or return when a new field note arrives.",end:"END OF CURRENT TRANSMISSION",question:"Have a question from the field?",reply:"Reply to Ryu"},ja:{world:"WORLD 04 · 受信ログ",title1:"世界と世界の間から届く",title2:"記録と考察。",index:"信号一覧",entries:"件を受信",labels:{TECH_BUSINESS:"開発ノート",TRAVEL_CULTURE:"旅のノート",SKI_SNOW:"雪山ノート"},filters:["すべて","開発","探検","雪山"],search:"記録を検索",signal:"信号",decode:"記録を読む",loading:"フィールドノートを受信中…",loadError:"アーカイブに接続できませんでした。",retry:"もう一度試す",empty:"この周波数に信号はありません。",emptyCopy:"別のチャンネルを試すか、新しい記録をお待ちください。",end:"現在の通信はここまで",question:"現場から質問がありますか？",reply:"Ryuに返信する"},zh:{world:"WORLD 04 · 接收讯息",title1:"来自世界之间的",title2:"笔记与思考。",index:"讯息索引",entries:"篇已接收",labels:{TECH_BUSINESS:"开发笔记",TRAVEL_CULTURE:"旅行笔记",SKI_SNOW:"雪山笔记"},filters:["全部讯息","开发","探索","雪山"],search:"搜索档案",signal:"讯息",decode:"读取内容",loading:"正在扫描旅行笔记…",loadError:"暂时无法连接档案。",retry:"重试",empty:"这个频率上没有讯息。",emptyCopy:"试试其他频道，或等待新的旅行笔记。",end:"当前讯息结束",question:"有来自旅途的问题吗？",reply:"回复 Ryu"}};
const values:(Category|null)[]=[null,"TECH_BUSINESS","TRAVEL_CULTURE","SKI_SNOW"];const excerpt=(value:string)=>value.replace(/<[^>]+>/g,"").slice(0,150)+(value.length>150?"…":"");
export default function BlogPage(){
  const {language}=useLanguage();const t=copy[language];const [posts,setPosts]=useState<ApiPost[]>([]);const [active,setActive]=useState<Category|null>(null);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
  const loadPosts=useCallback(async()=>{setLoading(true);setError(false);try{const response=await fetch("/api/blog",{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json();setPosts(Array.isArray(data)?data:[])}catch{setError(true)}finally{setLoading(false)}},[]);
  useEffect(()=>{loadPosts()},[loadPosts]);
  const filtered=posts.filter(post=>(!active||post.category===active)&&post.title.toLowerCase().includes(query.toLowerCase()));
  return <div className="journal-world"><FloatingButtons/><header className="journal-hero"><div><p><Radio size={14}/> {t.world}</p><h1>{t.title1}<br/><em>{t.title2}</em></h1></div><div className="journal-receiver"><span>{t.index}</span><strong>{String(posts.length).padStart(2,"0")}</strong><small>{t.entries}</small></div></header><section className="journal-controls"><div>{values.map((value,index)=><button key={String(value)} onClick={()=>setActive(value)} className={active===value?"active":""} aria-pressed={active===value}>{t.filters[index]}</button>)}</div><label><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.search} aria-label={t.search}/></label></section>
    {loading&&<div className="journal-loading" aria-live="polite"><Radio/>{t.loading}</div>}
    {error&&<div className="journal-load-error" role="alert"><BookOpen/><h2>{t.loadError}</h2><button onClick={loadPosts}><RefreshCw/>{t.retry}</button></div>}
    {!loading&&!error&&<main className="journal-grid">{filtered.map((post,index)=><article key={post.id} className={index===0?"featured":""}><Link href={`/blog/${post.slug}`} className="journal-image"><Image src={post.coverImage||"/images/astro.jpg"} alt="" fill sizes={index===0?"100vw":"(max-width:800px) 100vw, 33vw"}/><span>{t.labels[post.category]}</span></Link><div className="journal-copy"><small>{new Date(post.createdAt).toLocaleDateString(language==="ja"?"ja-JP":language==="zh"?"zh-CN":"en-GB",{day:"2-digit",month:"short",year:"numeric"})} · {t.signal} {String(index+1).padStart(2,"0")}</small><h2><Link href={`/blog/${post.slug}`}>{post.title}</Link></h2><p>{excerpt(post.content)}</p><Link href={`/blog/${post.slug}`} className="journal-open">{t.decode} <ArrowUpRight size={16}/></Link></div></article>)}</main>}
    {!loading&&!error&&!filtered.length&&<div className="journal-empty"><BookOpen size={30}/><h2>{t.empty}</h2><p>{t.emptyCopy}</p></div>}<section className="journal-cta"><p>{t.end}</p><h2>{t.question}</h2><Link href="/contact">{t.reply} <ArrowUpRight size={17}/></Link></section></div>
}
